console.log("clara".toLocaleUpperCase())
console.log("clara".toLocaleLowerCase())
console.log("Maria".charAt(2))
console.log("Maria".charAt(2))
console.log("Maria Clara Corre Mulher".trim())
console.log("Maria Clara Corre Mulher".concat('Rápido'))
console.log("Maria Clara Corre Mulher".includes('Rápidinho'))
console.log("Maria Clara Corre Mulher".startsWith('Maria'))
console.log("Maria Clara Corre Mulher".endsWith('r'))
console.log("Maria Clara Corre Mulher".indexOf('C'))
console.log("Maria Clara Corre Mulher".search('M'))
console.log("Maria Clara Corre Mulher".lastIndexOf('a'))
console.log("66".padStart(5,'+'))
console.log("66".padEnd(5,'+'))
console.log('*'.repeat(5))
console.log('javascript'.slice(0, 2))
console.log('Aparenetemente replaceAll não é uma função'.replace("a", "b"))

